/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CustomerList {
    }
    interface CustomerNew {
    }
    interface HomePage {
    }
    interface JobDetails {
    }
    interface JobList {
    }
    interface JobNew {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCustomerListElement extends Components.CustomerList, HTMLStencilElement {
    }
    var HTMLCustomerListElement: {
        prototype: HTMLCustomerListElement;
        new (): HTMLCustomerListElement;
    };
    interface HTMLCustomerNewElement extends Components.CustomerNew, HTMLStencilElement {
    }
    var HTMLCustomerNewElement: {
        prototype: HTMLCustomerNewElement;
        new (): HTMLCustomerNewElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLJobDetailsElement extends Components.JobDetails, HTMLStencilElement {
    }
    var HTMLJobDetailsElement: {
        prototype: HTMLJobDetailsElement;
        new (): HTMLJobDetailsElement;
    };
    interface HTMLJobListElement extends Components.JobList, HTMLStencilElement {
    }
    var HTMLJobListElement: {
        prototype: HTMLJobListElement;
        new (): HTMLJobListElement;
    };
    interface HTMLJobNewElement extends Components.JobNew, HTMLStencilElement {
    }
    var HTMLJobNewElement: {
        prototype: HTMLJobNewElement;
        new (): HTMLJobNewElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "customer-list": HTMLCustomerListElement;
        "customer-new": HTMLCustomerNewElement;
        "home-page": HTMLHomePageElement;
        "job-details": HTMLJobDetailsElement;
        "job-list": HTMLJobListElement;
        "job-new": HTMLJobNewElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CustomerList {
    }
    interface CustomerNew {
    }
    interface HomePage {
    }
    interface JobDetails {
    }
    interface JobList {
    }
    interface JobNew {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "customer-list": CustomerList;
        "customer-new": CustomerNew;
        "home-page": HomePage;
        "job-details": JobDetails;
        "job-list": JobList;
        "job-new": JobNew;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "customer-list": LocalJSX.CustomerList & JSXBase.HTMLAttributes<HTMLCustomerListElement>;
            "customer-new": LocalJSX.CustomerNew & JSXBase.HTMLAttributes<HTMLCustomerNewElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "job-details": LocalJSX.JobDetails & JSXBase.HTMLAttributes<HTMLJobDetailsElement>;
            "job-list": LocalJSX.JobList & JSXBase.HTMLAttributes<HTMLJobListElement>;
            "job-new": LocalJSX.JobNew & JSXBase.HTMLAttributes<HTMLJobNewElement>;
        }
    }
}
